### ISSUE TITLE
How to customize page timeout

### ISSUE THREAD

**Issue by zwying0814** [halillusion/vpjax#1]
Hello, man! Thanks for developing this project. I would like to know how to customize the page timeout period? Looking forward to your reply, good luck.

**Comment by halillusion** [comment]
Hey @zwying0814! 

First of all, thank you for your interest. It was not possible to customize the settings because I was developing it for hobby purposes and it was still in beta stage. But it started to offer this feature with v0.7.0. I've added example usage in its documentation as well.

I wish you good work. 

[v0.7.0](https://github.com/halillusion/vpjax/releases/tag/v0.7.0-beta.4)
